language: bash

services:
  - docker

jobs:
    include:
        - stage: test
        - script: docker build -t gnustep-clang-ubuntu1904 ubuntu-19.04-clang-8.0-runtime-2.0/testing/.;  docker run gnustep-clang-ubuntu1904 | grep -q "ARC is working"
        - script: docker build -t gnustep-clang-ubuntu1604 ubuntu-16.04-clang-6.0-runtime-1.9/testing/.;  docker run gnustep-clang-ubuntu1604 | grep -q "ARC is working"
        - script: docker build -t gnustep-clang-debian-10 debian-10-clang-8.0/testing/.;  docker run gnustep-clang-debian-10 | grep -q "ARC is working"
