language: bash

services:
  - docker

jobs:
    include:
        - stage: build_images
        - script: docker build -t gnustep-clang-ubuntu1904 ubuntu-19.04-clang-8.0-runtime-2.0/testing/.
        - script: docker build -t gnustep-clang-ubuntu1604 ubuntu-16.04-clang-6.0-runtime-1.9/testing/.
        - stage: test
        - script: docker run gnustep-clang-ubuntu1904 | grep -q "ARC is working"
        - script: docker run gnustep-clang-ubuntu1604 | grep -q "ARC is working"
