on:
  [push]
name: GNUstep on ubuntu-16.04-clang-6.0-runtime-1.9
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          cd ubuntu-16.04-clang-6.0-runtime-1.9
          sh ./test.sh
