on:
  [push]
name: GNUstep on Ubuntu 20.10
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          cd ubuntu-20.10-clang-11.0-runtime-2.0
          sh ./test.sh
